### ISSUE TITLE
Support International Domain Names (IDN)

### ISSUE THREAD

**Issue by ge0rg** [ge0rg/MemorizingTrustManager#20]
The new hostname verification popup shows the punycode-encoded hostnames, as this is the format used for SAN/CN. We need to pull in [libidn](http://www.gnu.org/s/libidn/) or a comparable library to display the UTF8 hostnames to the user. IDN==PITA.

**Comment by mimi89999** [comment]
Please don't do that.

**Comment by ge0rg** [comment]
Android 7 has introduced [native IDNA support](https://developer.android.com/reference/android/icu/text/IDNA) that we could make use of, conditionally based on Build number.

**Comment by Flowdalic** [comment]
You could (additionally) use [`IDN.toUnicode()`](https://developer.android.com/reference/java/net/IDN#toUnicode(java.lang.String)) which is available since API 9.

**Comment by ge0rg** [comment]
Thanks for the pointer, @Flowdalic, that would be really great. I think it would be appropriate to add the Unicode string in parens after each punycode SAN.

This code still has minSdk 7, but I don't see any issues to bump it up to around 14 where a need arises.
