### ISSUE TITLE
Is it possible to launch the MTM directly, rather than via HttpsUrlConnection

### ISSUE THREAD

**Issue by eliburke** [ge0rg/MemorizingTrustManager#39]
I have successfully used the MTM to connect to a web server, and I would also like to use it to display self-signed certificates for a non-HTTPS connection I make manually. I have an SSL verify callback that reaches up into the UI and will even block on a call to checkServerTrusted(), but no dialog is ever shown. 
Should this work and I'm just not doing it right?

    // initialize the MTM with an x509 store containing pinned certificates. 
    MemorizingTrustManager mtm = myObj.getMemorizingTrustManager();
     try {
        // here, I have tried with and without calling bindDisplayActivity
        //mtm.bindDisplayActivity(myActivity.instance());
        Log.d("I am printed");
        mtm.checkServerTrusted(certList, "ECDHE_RSA");
        Log.d("I am NOT printed");
    } catch (Exception e) {
        Log.d("MTM exception: " + e);
    }

Thanks for any response.

**Comment by ge0rg** [comment]
I have added a section to the README file that explains your use case. You need to add MTM to the default SSLContext, and do hostname checking manually at every socket connection:

	// register MemorizingTrustManager for all SSLSockets
	SSLContext sc = SSLContext.getInstance("TLS");
	MemorizingTrustManager mtm = new MemorizingTrustManager(this);
	HostnameVerifier hv = mtm.wrapHostnameVerifier(new org.apache.http.conn.ssl.StrictHostnameVerifier());
	sc.init(null, new X509TrustManager[] { mtm }, new java.security.SecureRandom());
	SSLContext.setDefault(sc);
	
	// connect a socket
	SSLSocket s = ...;
	s.startHandshake();
	if (!hv.verify(your_domain_name, sslSocket.getSession())) {
	    throw new CertificateException("Server failed to authenticate as " + your_domain_name);
	}
