### ISSUE TITLE
Feature request: deleteCertificates()

### ISSUE THREAD

**Issue by rfc2822** [ge0rg/MemorizingTrustManager#45]
In many use cases, apps may want to delete all MTM-trusted certificates (especially if they don't provide a UI that allows to view and edit all trusted certificates, but only a "Reset all trusted certificates" option).

Currently, there's `getCertificates()` and `deleteCertificate()`, so we can iterate through all certificates, but I think a `deleteCertificates()` method that deletes all certificates would be useful.

I can provide a pull request for that if you like, but it may take some time.

**Comment by ge0rg** [comment]
Yes, that sounds like a useful feature. I'd suggest naming it `deleteAllCertificates()` though. I can't implement it on short notice either, so feel free to provide a PR :)
