### ISSUE TITLE
Proguard error on Android SDK 23

### ISSUE THREAD

**Issue by klassm** [ge0rg/MemorizingTrustManager#47]
Your library cannot be used together with Android sdk 23, as proguard throws an error:

Warning: de.duenndns.ssl.MemorizingTrustManager: can't find referenced method 'void setLatestEventInfo(android.content.Context,java.lang.CharSequence,java.lang.CharSequence,android.app.PendingIntent)' in library class android.app.Notification

This is a real show stopper - with that dependency your library cannot be used any more.

**Comment by klassm** [comment]
There seems to be a pull request to solve this issue: https://github.com/ge0rg/MemorizingTrustManager/pull/46

When will be your next release fixing that issue? :-)

**Comment by klassm** [comment]
See https://github.com/klassm/MemorizingTrustManager/commit/42254987aaea7a207712f3f0b799b3cf2d845dcf 

I've merged those two available pull requests allowing to build an aar that can be used against sdk 23. I won't create a pull request - feel free to take what you want.

**Comment by ge0rg** [comment]
Fixed in master! :)
