### ISSUE TITLE
Allow MemorizingTrustManager to be called on the UI thread

### ISSUE THREAD

**Issue by klassm** [ge0rg/MemorizingTrustManager#50]
Currently this will result in an ANR, as wait() is called on the UI thread.

**Comment by ge0rg** [comment]
Sorry, but MTM is always called on the thread of your network connection, and if you do networking on the UI thread, nobody can help you. You should refactor your networking code into a background thread, Service or AsyncTask.

**Comment by klassm** [comment]
Not really. See #51

**Comment by ge0rg** [comment]
I presume you are handling the [onReceivedSslError()](http://developer.android.com/reference/android/webkit/WebViewClient.html#onReceivedSslError(android.webkit.WebView, android.webkit.SslErrorHandler, android.net.http.SslError)) callback? That method provides you with an SslErrorHandler instance that you need to forward the decision to, asynchronously.

To allow async usage, either MTM needs to be rewritten, with a blocker thread introduced to handle the existing primary case, or a wrapper Thread needs to be added that can be blocked by MTM and call the correct response handler after the user's decision.

Such a wrapper would be very tiny (an anonymous Thread instance should suffice), and it would need to expose some callback API to the application. As you already have a case-specific callback API (SslErrorHandler), you will be writing a thin wrapper around a thin wrapper around a blocking thread.

To reduce complexity, it would be easier and more straight-forward to just wrap MTM in a Thread that  does call the appropriate SslErrorHandler method after MTM's (blocking) completion.

**Comment by klassm** [comment]
This is exactly what I currently do - but at least exposing the Api method for mtm would be great ...
